# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Distortion/Pedal
else:
    import _Distortion/Pedal

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class StereoSample(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    outL = property(_Distortion/Pedal.StereoSample_outL_get, _Distortion/Pedal.StereoSample_outL_set)
    outR = property(_Distortion/Pedal.StereoSample_outR_get, _Distortion/Pedal.StereoSample_outR_set)

    def __init__(self, *args):
        _Distortion/Pedal.StereoSample_swiginit(self, _Distortion/Pedal.new_StereoSample(*args))
    __swig_destroy__ = _Distortion/Pedal.delete_StereoSample

# Register StereoSample in _Distortion/Pedal:
_Distortion/Pedal.StereoSample_swigregister(StereoSample)

class ComplexSample(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    real = property(_Distortion/Pedal.ComplexSample_real_get, _Distortion/Pedal.ComplexSample_real_set)
    imag = property(_Distortion/Pedal.ComplexSample_imag_get, _Distortion/Pedal.ComplexSample_imag_set)

    def __init__(self, *args):
        _Distortion/Pedal.ComplexSample_swiginit(self, _Distortion/Pedal.new_ComplexSample(*args))
    __swig_destroy__ = _Distortion/Pedal.delete_ComplexSample

# Register ComplexSample in _Distortion/Pedal:
_Distortion/Pedal.ComplexSample_swigregister(ComplexSample)

class Module(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_Module

    def __init__(self):
        _Distortion/Pedal.Module_swiginit(self, _Distortion/Pedal.new_Module())

# Register Module in _Distortion/Pedal:
_Distortion/Pedal.Module_swigregister(Module)

class Generator(Module):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_Generator

    def process(self):
        return _Distortion/Pedal.Generator_process(self)

    def __call__(self):
        return _Distortion/Pedal.Generator___call__(self)

# Register Generator in _Distortion/Pedal:
_Distortion/Pedal.Generator_swigregister(Generator)

class ComplexGenerator(Module):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_ComplexGenerator

    def process(self):
        return _Distortion/Pedal.ComplexGenerator_process(self)

# Register ComplexGenerator in _Distortion/Pedal:
_Distortion/Pedal.ComplexGenerator_swigregister(ComplexGenerator)

class Function(Module):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_Function

    def process(self, input):
        return _Distortion/Pedal.Function_process(self, input)

    def __call__(self, input):
        return _Distortion/Pedal.Function___call__(self, input)

# Register Function in _Distortion/Pedal:
_Distortion/Pedal.Function_swigregister(Function)

class ComplexFunction(Module):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_ComplexFunction

    def process(self, input):
        return _Distortion/Pedal.ComplexFunction_process(self, input)

# Register ComplexFunction in _Distortion/Pedal:
_Distortion/Pedal.ComplexFunction_swigregister(ComplexFunction)

class Function2(Module):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_Function2

    def process(self, input1, input2):
        return _Distortion/Pedal.Function2_process(self, input1, input2)

# Register Function2 in _Distortion/Pedal:
_Distortion/Pedal.Function2_swigregister(Function2)

class FunctionN(Module):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distortion/Pedal.delete_FunctionN

    def process(self, input, n):
        return _Distortion/Pedal.FunctionN_process(self, input, n)

# Register FunctionN in _Distortion/Pedal:
_Distortion/Pedal.FunctionN_swigregister(FunctionN)

class Value(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    value = property(_Distortion/Pedal.Value_value_get, _Distortion/Pedal.Value_value_set)

    def __init__(self, v=0.0):
        _Distortion/Pedal.Value_swiginit(self, _Distortion/Pedal.new_Value(v))

    def set_value(self, v):
        return _Distortion/Pedal.Value_set_value(self, v)

    def process(self):
        return _Distortion/Pedal.Value_process(self)
    __swig_destroy__ = _Distortion/Pedal.delete_Value

# Register Value in _Distortion/Pedal:
_Distortion/Pedal.Value_swigregister(Value)

class GeneratorGroup(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Distortion/Pedal.GeneratorGroup_swiginit(self, _Distortion/Pedal.new_GeneratorGroup())
    __swig_destroy__ = _Distortion/Pedal.delete_GeneratorGroup

    def addMod(self, p):
        return _Distortion/Pedal.GeneratorGroup_addMod(self, p)

    def process(self):
        return _Distortion/Pedal.GeneratorGroup_process(self)

# Register GeneratorGroup in _Distortion/Pedal:
_Distortion/Pedal.GeneratorGroup_swigregister(GeneratorGroup)

class ParallelFunctionVector(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Distortion/Pedal.ParallelFunctionVector_swiginit(self, _Distortion/Pedal.new_ParallelFunctionVector())
    __swig_destroy__ = _Distortion/Pedal.delete_ParallelFunctionVector

    def addFilter(self, dsp):
        return _Distortion/Pedal.ParallelFunctionVector_addFilter(self, dsp)

    def process(self, input):
        return _Distortion/Pedal.ParallelFunctionVector_process(self, input)

# Register ParallelFunctionVector in _Distortion/Pedal:
_Distortion/Pedal.ParallelFunctionVector_swigregister(ParallelFunctionVector)

class SerialFunctionVector(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Distortion/Pedal.SerialFunctionVector_swiginit(self, _Distortion/Pedal.new_SerialFunctionVector())
    __swig_destroy__ = _Distortion/Pedal.delete_SerialFunctionVector

    def addFilter(self, node):
        return _Distortion/Pedal.SerialFunctionVector_addFilter(self, node)

    def process(self, input):
        return _Distortion/Pedal.SerialFunctionVector_process(self, input)

    def size(self):
        return _Distortion/Pedal.SerialFunctionVector_size(self)

# Register SerialFunctionVector in _Distortion/Pedal:
_Distortion/Pedal.SerialFunctionVector_swigregister(SerialFunctionVector)

class Engine(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Distortion/Pedal.Engine_swiginit(self, _Distortion/Pedal.new_Engine())
    __swig_destroy__ = _Distortion/Pedal.delete_Engine

    def addGen(self, gen):
        return _Distortion/Pedal.Engine_addGen(self, gen)

    def addFilter(self, filt):
        return _Distortion/Pedal.Engine_addFilter(self, filt)

    def process(self):
        return _Distortion/Pedal.Engine_process(self)

# Register Engine in _Distortion/Pedal:
_Distortion/Pedal.Engine_swigregister(Engine)


def set_samplerate(sampleRate):
    return _Distortion/Pedal.set_samplerate(sampleRate)

def get_samplerate():
    return _Distortion/Pedal.get_samplerate()
class Ramped(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, initValue=0.0):
        _Distortion/Pedal.Ramped_swiginit(self, _Distortion/Pedal.new_Ramped(initValue))

    def set(self, value):
        return _Distortion/Pedal.Ramped_set(self, value)

    def value(self):
        return _Distortion/Pedal.Ramped_value(self)

    def target(self, *args):
        return _Distortion/Pedal.Ramped_target(self, *args)

    def process(self):
        return _Distortion/Pedal.Ramped_process(self)

    def __call__(self):
        return _Distortion/Pedal.Ramped___call__(self)

    def run(self, output, n):
        return _Distortion/Pedal.Ramped_run(self, output, n)

    def targetMs(self, value, timeMs):
        return _Distortion/Pedal.Ramped_targetMs(self, value, timeMs)
    __swig_destroy__ = _Distortion/Pedal.delete_Ramped

# Register Ramped in _Distortion/Pedal:
_Distortion/Pedal.Ramped_swigregister(Ramped)

class Parameter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    _value = property(_Distortion/Pedal.Parameter__value_get, _Distortion/Pedal.Parameter__value_set)

    def __init__(self, v):
        _Distortion/Pedal.Parameter_swiginit(self, _Distortion/Pedal.new_Parameter(v))
    __swig_destroy__ = _Distortion/Pedal.delete_Parameter

    def set(self, v):
        return _Distortion/Pedal.Parameter_set(self, v)

    def __call__(self):
        return _Distortion/Pedal.Parameter___call__(self)

    def process(self):
        return _Distortion/Pedal.Parameter_process(self)

# Register Parameter in _Distortion/Pedal:
_Distortion/Pedal.Parameter_swigregister(Parameter)

class ParamLinear(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, initial=0., ms=15.0):
        _Distortion/Pedal.ParamLinear_swiginit(self, _Distortion/Pedal.new_ParamLinear(initial, ms))

    def set(self, v):
        return _Distortion/Pedal.ParamLinear_set(self, v)

    def process(self):
        return _Distortion/Pedal.ParamLinear_process(self)

    def __call__(self):
        return _Distortion/Pedal.ParamLinear___call__(self)

    def setTime(self, ms):
        return _Distortion/Pedal.ParamLinear_setTime(self, ms)

    def isRamping(self):
        return _Distortion/Pedal.ParamLinear_isRamping(self)

    def value(self):
        return _Distortion/Pedal.ParamLinear_value(self)
    __swig_destroy__ = _Distortion/Pedal.delete_ParamLinear

# Register ParamLinear in _Distortion/Pedal:
_Distortion/Pedal.ParamLinear_swigregister(ParamLinear)

class ParamSlew(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, initial=0., timeMs=15.):
        _Distortion/Pedal.ParamSlew_swiginit(self, _Distortion/Pedal.new_ParamSlew(initial, timeMs))

    def set(self, v):
        return _Distortion/Pedal.ParamSlew_set(self, v)

    def process(self):
        return _Distortion/Pedal.ParamSlew_process(self)

    def __call__(self):
        return _Distortion/Pedal.ParamSlew___call__(self)

    def setTime(self, ms):
        return _Distortion/Pedal.ParamSlew_setTime(self, ms)
    __swig_destroy__ = _Distortion/Pedal.delete_ParamSlew

# Register ParamSlew in _Distortion/Pedal:
_Distortion/Pedal.ParamSlew_swigregister(ParamSlew)

class Smoother(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    P_NONE = _Distortion/Pedal.Smoother_P_NONE
    P_LINEAR = _Distortion/Pedal.Smoother_P_LINEAR
    P_SLEW = _Distortion/Pedal.Smoother_P_SLEW
    _linparam = property(_Distortion/Pedal.Smoother__linparam_get, _Distortion/Pedal.Smoother__linparam_set)
    _slewparam = property(_Distortion/Pedal.Smoother__slewparam_get, _Distortion/Pedal.Smoother__slewparam_set)
    _type = property(_Distortion/Pedal.Smoother__type_get, _Distortion/Pedal.Smoother__type_set)
    lastVal = property(_Distortion/Pedal.Smoother_lastVal_get, _Distortion/Pedal.Smoother_lastVal_set)

    def __init__(self):
        _Distortion/Pedal.Smoother_swiginit(self, _Distortion/Pedal.new_Smoother())
    __swig_destroy__ = _Distortion/Pedal.delete_Smoother

    def __call__(self):
        return _Distortion/Pedal.Smoother___call__(self)

    def setType(self, t):
        return _Distortion/Pedal.Smoother_setType(self, t)

    def set(self, v):
        return _Distortion/Pedal.Smoother_set(self, v)

    def setTime(self, ms):
        return _Distortion/Pedal.Smoother_setTime(self, ms)

    def process(self):
        return _Distortion/Pedal.Smoother_process(self)

# Register Smoother in _Distortion/Pedal:
_Distortion/Pedal.Smoother_swigregister(Smoother)

class Modulator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    modIn = property(_Distortion/Pedal.Modulator_modIn_get, _Distortion/Pedal.Modulator_modIn_set)
    modAmount = property(_Distortion/Pedal.Modulator_modAmount_get, _Distortion/Pedal.Modulator_modAmount_set)
    modScale = property(_Distortion/Pedal.Modulator_modScale_get, _Distortion/Pedal.Modulator_modScale_set)
    modMin = property(_Distortion/Pedal.Modulator_modMin_get, _Distortion/Pedal.Modulator_modMin_set)
    modMax = property(_Distortion/Pedal.Modulator_modMax_get, _Distortion/Pedal.Modulator_modMax_set)
    lastVal = property(_Distortion/Pedal.Modulator_lastVal_get, _Distortion/Pedal.Modulator_lastVal_set)
    bUnipolar = property(_Distortion/Pedal.Modulator_bUnipolar_get, _Distortion/Pedal.Modulator_bUnipolar_set)

    def __init__(self):
        _Distortion/Pedal.Modulator_swiginit(self, _Distortion/Pedal.new_Modulator())
    __swig_destroy__ = _Distortion/Pedal.delete_Modulator

    def set(self, v):
        return _Distortion/Pedal.Modulator_set(self, v)

    def process(self, *args):
        return _Distortion/Pedal.Modulator_process(self, *args)

    def __call__(self, *args):
        return _Distortion/Pedal.Modulator___call__(self, *args)

    def mod(self):
        return _Distortion/Pedal.Modulator_mod(self)

# Register Modulator in _Distortion/Pedal:
_Distortion/Pedal.Modulator_swigregister(Modulator)

class ModGenerator(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def process(self):
        return _Distortion/Pedal.ModGenerator_process(self)

    def setFM(self, f):
        return _Distortion/Pedal.ModGenerator_setFM(self, f)

    def setPM(self, f):
        return _Distortion/Pedal.ModGenerator_setPM(self, f)

    def setAM(self, f):
        return _Distortion/Pedal.ModGenerator_setAM(self, f)

    def setRatio(self, f):
        return _Distortion/Pedal.ModGenerator_setRatio(self, f)

    def setIndex(self, f):
        return _Distortion/Pedal.ModGenerator_setIndex(self, f)
    baseFreq = property(_Distortion/Pedal.ModGenerator_baseFreq_get, _Distortion/Pedal.ModGenerator_baseFreq_set)
    fm = property(_Distortion/Pedal.ModGenerator_fm_get, _Distortion/Pedal.ModGenerator_fm_set)
    pm = property(_Distortion/Pedal.ModGenerator_pm_get, _Distortion/Pedal.ModGenerator_pm_set)
    am = property(_Distortion/Pedal.ModGenerator_am_get, _Distortion/Pedal.ModGenerator_am_set)
    ratio = property(_Distortion/Pedal.ModGenerator_ratio_get, _Distortion/Pedal.ModGenerator_ratio_set)
    index = property(_Distortion/Pedal.ModGenerator_index_get, _Distortion/Pedal.ModGenerator_index_set)
    __swig_destroy__ = _Distortion/Pedal.delete_ModGenerator

# Register ModGenerator in _Distortion/Pedal:
_Distortion/Pedal.ModGenerator_swigregister(ModGenerator)

class ModFilter1(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def process(self, input):
        return _Distortion/Pedal.ModFilter1_process(self, input)

    def setCutoff(self, f):
        return _Distortion/Pedal.ModFilter1_setCutoff(self, f)

    def setFM(self, f):
        return _Distortion/Pedal.ModFilter1_setFM(self, f)

    def setAM(self, a):
        return _Distortion/Pedal.ModFilter1_setAM(self, a)
    __swig_destroy__ = _Distortion/Pedal.delete_ModFilter1

# Register ModFilter1 in _Distortion/Pedal:
_Distortion/Pedal.ModFilter1_swigregister(ModFilter1)

class ModFilter2(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def process(self, input):
        return _Distortion/Pedal.ModFilter2_process(self, input)

    def setCutoff(self, f):
        return _Distortion/Pedal.ModFilter2_setCutoff(self, f)

    def setWidth(self, f):
        return _Distortion/Pedal.ModFilter2_setWidth(self, f)

    def setFM(self, f):
        return _Distortion/Pedal.ModFilter2_setFM(self, f)

    def setWM(self, w):
        return _Distortion/Pedal.ModFilter2_setWM(self, w)

    def setAM(self, a):
        return _Distortion/Pedal.ModFilter2_setAM(self, a)
    __swig_destroy__ = _Distortion/Pedal.delete_ModFilter2

# Register ModFilter2 in _Distortion/Pedal:
_Distortion/Pedal.ModFilter2_swigregister(ModFilter2)

class ModFilter(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def process(self, input):
        return _Distortion/Pedal.ModFilter_process(self, input)

    def setCutoff(self, f):
        return _Distortion/Pedal.ModFilter_setCutoff(self, f)

    def setRes(self, f):
        return _Distortion/Pedal.ModFilter_setRes(self, f)

    def setFM(self, f):
        return _Distortion/Pedal.ModFilter_setFM(self, f)

    def setQM(self, r):
        return _Distortion/Pedal.ModFilter_setQM(self, r)

    def setAM(self, a):
        return _Distortion/Pedal.ModFilter_setAM(self, a)

    def setIM(self, a):
        return _Distortion/Pedal.ModFilter_setIM(self, a)

    def setFBM(self, a):
        return _Distortion/Pedal.ModFilter_setFBM(self, a)
    __swig_destroy__ = _Distortion/Pedal.delete_ModFilter

# Register ModFilter in _Distortion/Pedal:
_Distortion/Pedal.ModFilter_swigregister(ModFilter)

class ModDelay(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, maxDelay=2.0, initDelay=0.5):
        _Distortion/Pedal.ModDelay_swiginit(self, _Distortion/Pedal.new_ModDelay(maxDelay, initDelay))
    __swig_destroy__ = _Distortion/Pedal.delete_ModDelay

    def setDM(self, v):
        return _Distortion/Pedal.ModDelay_setDM(self, v)

    def setFBM(self, v):
        return _Distortion/Pedal.ModDelay_setFBM(self, v)

    def setMIXM(self, v):
        return _Distortion/Pedal.ModDelay_setMIXM(self, v)

    def setIM(self, v):
        return _Distortion/Pedal.ModDelay_setIM(self, v)

    def setAM(self, v):
        return _Distortion/Pedal.ModDelay_setAM(self, v)

    def setDelay(self, d):
        return _Distortion/Pedal.ModDelay_setDelay(self, d)

    def setFeedback(self, f):
        return _Distortion/Pedal.ModDelay_setFeedback(self, f)

    def setMix(self, m):
        return _Distortion/Pedal.ModDelay_setMix(self, m)

    def setIpolType(self, type):
        return _Distortion/Pedal.ModDelay_setIpolType(self, type)

    def getDelay(self):
        return _Distortion/Pedal.ModDelay_getDelay(self)

    def process(self, input):
        return _Distortion/Pedal.ModDelay_process(self, input)

    def read(self, *args):
        return _Distortion/Pedal.ModDelay_read(self, *args)

    def write(self, v):
        return _Distortion/Pedal.ModDelay_write(self, v)
    dm = property(_Distortion/Pedal.ModDelay_dm_get, _Distortion/Pedal.ModDelay_dm_set)
    fbm = property(_Distortion/Pedal.ModDelay_fbm_get, _Distortion/Pedal.ModDelay_fbm_set)
    mixm = property(_Distortion/Pedal.ModDelay_mixm_get, _Distortion/Pedal.ModDelay_mixm_set)
    im = property(_Distortion/Pedal.ModDelay_im_get, _Distortion/Pedal.ModDelay_im_set)
    am = property(_Distortion/Pedal.ModDelay_am_get, _Distortion/Pedal.ModDelay_am_set)
    mBaseDelay = property(_Distortion/Pedal.ModDelay_mBaseDelay_get, _Distortion/Pedal.ModDelay_mBaseDelay_set)
    mBaseFeedback = property(_Distortion/Pedal.ModDelay_mBaseFeedback_get, _Distortion/Pedal.ModDelay_mBaseFeedback_set)
    mBaseMix = property(_Distortion/Pedal.ModDelay_mBaseMix_get, _Distortion/Pedal.ModDelay_mBaseMix_set)

# Register ModDelay in _Distortion/Pedal:
_Distortion/Pedal.ModDelay_swigregister(ModDelay)

class ModSine(ModGenerator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, f):
        _Distortion/Pedal.ModSine_swiginit(self, _Distortion/Pedal.new_ModSine(f))

    def setFreq(self, f):
        return _Distortion/Pedal.ModSine_setFreq(self, f)

    def process(self):
        return _Distortion/Pedal.ModSine_process(self)
    __swig_destroy__ = _Distortion/Pedal.delete_ModSine

# Register ModSine in _Distortion/Pedal:
_Distortion/Pedal.ModSine_swigregister(ModSine)

class Sine(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, f):
        _Distortion/Pedal.Sine_swiginit(self, _Distortion/Pedal.new_Sine(f))

    def setFreq(self, f):
        return _Distortion/Pedal.Sine_setFreq(self, f)

    def process(self):
        return _Distortion/Pedal.Sine_process(self)
    __swig_destroy__ = _Distortion/Pedal.delete_Sine

# Register Sine in _Distortion/Pedal:
_Distortion/Pedal.Sine_swigregister(Sine)

class LFO(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    SINE = _Distortion/Pedal.LFO_SINE
    SINE_PARA = _Distortion/Pedal.LFO_SINE_PARA
    COS = _Distortion/Pedal.LFO_COS
    COS_CUBIC = _Distortion/Pedal.LFO_COS_CUBIC
    SAW_DOWN = _Distortion/Pedal.LFO_SAW_DOWN
    SAW_UP = _Distortion/Pedal.LFO_SAW_UP
    TRIANGLE = _Distortion/Pedal.LFO_TRIANGLE
    SQUARE = _Distortion/Pedal.LFO_SQUARE
    PULSE = _Distortion/Pedal.LFO_PULSE
    PARABOLA = _Distortion/Pedal.LFO_PARABOLA
    STAIR = _Distortion/Pedal.LFO_STAIR
    IMPULSE = _Distortion/Pedal.LFO_IMPULSE
    HANN = _Distortion/Pedal.LFO_HANN
    EVEN3 = _Distortion/Pedal.LFO_EVEN3
    EVEN5 = _Distortion/Pedal.LFO_EVEN5
    LINE2 = _Distortion/Pedal.LFO_LINE2
    UP2 = _Distortion/Pedal.LFO_UP2
    PATTERN = _Distortion/Pedal.LFO_PATTERN
    S1 = _Distortion/Pedal.LFO_S1
    C2 = _Distortion/Pedal.LFO_C2
    S3 = _Distortion/Pedal.LFO_S3
    C4 = _Distortion/Pedal.LFO_C4
    S5 = _Distortion/Pedal.LFO_S5
    COS_CUBU = _Distortion/Pedal.LFO_COS_CUBU
    DOWNU = _Distortion/Pedal.LFO_DOWNU
    IMPU = _Distortion/Pedal.LFO_IMPU
    LINE2U = _Distortion/Pedal.LFO_LINE2U
    PARAU = _Distortion/Pedal.LFO_PARAU
    STAIRU = _Distortion/Pedal.LFO_STAIRU
    TRIU = _Distortion/Pedal.LFO_TRIU
    UPU = _Distortion/Pedal.LFO_UPU
    UP2U = _Distortion/Pedal.LFO_UP2U

    def __init__(self, *args):
        _Distortion/Pedal.LFO_swiginit(self, _Distortion/Pedal.new_LFO(*args))

    def setFreq(self, f):
        return _Distortion/Pedal.LFO_setFreq(self, f)

    def setPeriod(self, seconds):
        return _Distortion/Pedal.LFO_setPeriod(self, seconds)

    def setPhase(self, p):
        return _Distortion/Pedal.LFO_setPhase(self, p)

    def setMod(self, m):
        return _Distortion/Pedal.LFO_setMod(self, m)

    def setWave(self, w):
        return _Distortion/Pedal.LFO_setWave(self, w)

    def tick(self):
        return _Distortion/Pedal.LFO_tick(self)

    def process(self):
        return _Distortion/Pedal.LFO_process(self)

    def reset(self):
        return _Distortion/Pedal.LFO_reset(self)

    def run(self, output, n):
        return _Distortion/Pedal.LFO_run(self, output, n)

    def setUnipolar(self, v):
        return _Distortion/Pedal.LFO_setUnipolar(self, v)

    def phaseAdd(self, p):
        return _Distortion/Pedal.LFO_phaseAdd(self, p)

    def freq(self, *args):
        return _Distortion/Pedal.LFO_freq(self, *args)

    def __call__(self):
        return _Distortion/Pedal.LFO___call__(self)
    __swig_destroy__ = _Distortion/Pedal.delete_LFO

# Register LFO in _Distortion/Pedal:
_Distortion/Pedal.LFO_swigregister(LFO)

class AD(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, attack=0.01, decay=0.1, level=1.0, curve=-4.0):
        _Distortion/Pedal.AD_swiginit(self, _Distortion/Pedal.new_AD(attack, decay, level, curve))

    def setAttack(self, seconds):
        return _Distortion/Pedal.AD_setAttack(self, seconds)

    def setDecay(self, seconds):
        return _Distortion/Pedal.AD_setDecay(self, seconds)

    def setLevel(self, level):
        return _Distortion/Pedal.AD_setLevel(self, level)

    def setCurve(self, curve):
        return _Distortion/Pedal.AD_setCurve(self, curve)

    def trigger(self):
        return _Distortion/Pedal.AD_trigger(self)

    def reset(self):
        return _Distortion/Pedal.AD_reset(self)

    def done(self):
        return _Distortion/Pedal.AD_done(self)

    def process(self):
        return _Distortion/Pedal.AD_process(self)

    def run(self, output, n):
        return _Distortion/Pedal.AD_run(self, output, n)
    __swig_destroy__ = _Distortion/Pedal.delete_AD

# Register AD in _Distortion/Pedal:
_Distortion/Pedal.AD_swigregister(AD)

class ADSR(Generator):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, attack=0.01, decay=0.1, sustain=0.7, release=0.3, level=1.0, curve=-4.0):
        _Distortion/Pedal.ADSR_swiginit(self, _Distortion/Pedal.new_ADSR(attack, decay, sustain, release, level, curve))

    def setAttack(self, seconds):
        return _Distortion/Pedal.ADSR_setAttack(self, seconds)

    def setDecay(self, seconds):
        return _Distortion/Pedal.ADSR_setDecay(self, seconds)

    def setSustain(self, level):
        return _Distortion/Pedal.ADSR_setSustain(self, level)

    def setRelease(self, seconds):
        return _Distortion/Pedal.ADSR_setRelease(self, seconds)

    def setLevel(self, level):
        return _Distortion/Pedal.ADSR_setLevel(self, level)

    def setCurve(self, curve):
        return _Distortion/Pedal.ADSR_setCurve(self, curve)

    def noteOn(self):
        return _Distortion/Pedal.ADSR_noteOn(self)

    def noteOff(self):
        return _Distortion/Pedal.ADSR_noteOff(self)

    def reset(self):
        return _Distortion/Pedal.ADSR_reset(self)

    def done(self):
        return _Distortion/Pedal.ADSR_done(self)

    def process(self):
        return _Distortion/Pedal.ADSR_process(self)

    def run(self, output, n):
        return _Distortion/Pedal.ADSR_run(self, output, n)
    __swig_destroy__ = _Distortion/Pedal.delete_ADSR

# Register ADSR in _Distortion/Pedal:
_Distortion/Pedal.ADSR_swigregister(ADSR)

class Pedal(Function):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Distortion/Pedal.Pedal_swiginit(self, _Distortion/Pedal.new_Pedal())

    def setDrive(self, v):
        return _Distortion/Pedal.Pedal_setDrive(self, v)

    def setBias(self, v):
        return _Distortion/Pedal.Pedal_setBias(self, v)

    def setAsym(self, v):
        return _Distortion/Pedal.Pedal_setAsym(self, v)

    def setOutput(self, v):
        return _Distortion/Pedal.Pedal_setOutput(self, v)

    def setTubeFeel(self, v):
        return _Distortion/Pedal.Pedal_setTubeFeel(self, v)

    def setSag(self, v):
        return _Distortion/Pedal.Pedal_setSag(self, v)

    def setType(self, t):
        return _Distortion/Pedal.Pedal_setType(self, t)

    def process(self, x):
        return _Distortion/Pedal.Pedal_process(self, x)

    def setMacroDrive(self, v):
        return _Distortion/Pedal.Pedal_setMacroDrive(self, v)

    def applyMacroDrive(self):
        return _Distortion/Pedal.Pedal_applyMacroDrive(self)

    def getWaveShaper(self):
        return _Distortion/Pedal.Pedal_getWaveShaper(self)

    def getPresence(self):
        return _Distortion/Pedal.Pedal_getPresence(self)

    def getTubeFeel(self):
        return _Distortion/Pedal.Pedal_getTubeFeel(self)

    def getPowerSag(self):
        return _Distortion/Pedal.Pedal_getPowerSag(self)
    __swig_destroy__ = _Distortion/Pedal.delete_Pedal

# Register Pedal in _Distortion/Pedal:
_Distortion/Pedal.Pedal_swigregister(Pedal)



